"""
Business Report Formatter for Professional Output
Returns both plain text (for downloads) and HTML (for display)
"""
from datetime import datetime
from typing import Dict, List, Any, Optional
import json


class BusinessReportFormatter:
    """
    Formats business insight cards into professional reports
    Returns both plain text and HTML versions
    """

    def __init__(self):
        self.report_date = datetime.now().strftime("%B %d, %Y")
        self.report_time = datetime.now().strftime("%I:%M %p")

    def _get_rating_from_percentage(self, value: float, thresholds: dict) -> tuple:
        """Determine performance rating and badge class from value"""
        if value <= thresholds.get("excellent", 25):
            return "Excellent", "excellent", "🟢"
        elif value <= thresholds.get("good", 30):
            return "Good", "good", "🟡"
        elif value <= thresholds.get("acceptable", 35):
            return "Acceptable", "acceptable", "🟠"
        else:
            return "Needs Improvement", "needs-improvement", "🔴"

    def format_metric_card(self, title: str, calculation: str, example: str,
                          interpretation: str, recommendations: List[str] = None) -> dict:
        """
        Format a single metric card into professional report sections
        Returns dict with 'text' and 'html' keys
        """
        # Deduplicate recommendations (preserve order, case-insensitive)
        if recommendations and isinstance(recommendations, (list, tuple)):
            seen = set()
            deduped = []
            for rec in recommendations:
                s = str(rec).strip().rstrip(".,;:")
                key = s.lower()
                if not key:
                    continue
                if key in seen:
                    continue
                seen.add(key)
                deduped.append(s)
            recommendations = deduped

        # Plain text version
        text = f"""
{'='*80}
{title.upper()}
{'='*80}

CALCULATION METHODOLOGY:
{calculation}

EXAMPLE CALCULATION:
{example}

ANALYSIS & INTERPRETATION:
{interpretation}
"""
        if recommendations:
            text += "\nRECOMMENDATIONS:\n"
            for i, rec in enumerate(recommendations, 1):
                text += f"{i}. {rec}\n"
        text += f"\n{'='*80}\n"

        # HTML version
        rec_html = ""
        if recommendations:
            rec_items = "".join(f"<li>{rec}</li>" for rec in recommendations)
            rec_html = f"<div class='recommendations'><h4>Recommendations</h4><ol>{rec_items}</ol></div>"

        html = f"""
        <div class="metric-card">
            <h3>{title}</h3>
            <div class="metric-calculation">
                <strong>Calculation:</strong> {calculation}
            </div>
            <div class="metric-example">
                <strong>Example:</strong> {example}
            </div>
            <div class="metric-interpretation">
                <p>{interpretation}</p>
            </div>
            {rec_html}
        </div>
        """

        return {"text": text, "html": html}

    def format_comprehensive_report(self, title: str, metrics: List[Dict],
                                  executive_summary: str = None, rating: str = "Good") -> dict:
        """
        Format multiple metrics into a comprehensive business report
        Returns dict with 'text' and 'html' keys
        """
        # Determine rating badge class
        badge_class = rating.lower().replace(' ', '-').replace('_', '-')
        
        # Tone and comparison text based on rating
        if rating in ["Excellent", "Good"]:
            tone = "excellent" if rating == "Excellent" else "good"
            comp = "exceeds" if rating == "Excellent" else "meets"
        elif rating == "Acceptable":
            tone = "acceptable"
            comp = "meets"
        else:
            tone = "concerning"
            comp = "falls below"

        # Plain text version
        text = f"""
{'='*80}
BUSINESS INTELLIGENCE REPORT
{title.upper()}
{'='*80}

Report Date: {self.report_date}
Generated Time: {self.report_time}

"""
        if executive_summary:
            text += f"EXECUTIVE SUMMARY:\n{executive_summary}\n\n{'='*80}\n\n"

        for metric in metrics:
            result = self.format_metric_card(
                title=metric.get('title', 'Metric'),
                calculation=metric.get('calculation', ''),
                example=metric.get('example', ''),
                interpretation=metric.get('interpretation', ''),
                recommendations=metric.get('recommendations', [])
            )
            text += result["text"]

        text += f"""
{'='*80}
END OF REPORT
{'='*80}

Generated by Hospitality AI Agent
For more insights, visit your dashboard or chat with our AI assistant.
"""

        # HTML version - using the glassmorphism style
        metrics_html = ""
        for metric in metrics:
            result = self.format_metric_card(
                title=metric.get('title', 'Metric'),
                calculation=metric.get('calculation', ''),
                example=metric.get('example', ''),
                interpretation=metric.get('interpretation', ''),
                recommendations=metric.get('recommendations', [])
            )
            metrics_html += result["html"]

        exec_summary_html = f"<p class='lead'>{executive_summary}</p>" if executive_summary else f"<p class='lead'>This {title.lower()} reveals <strong>{tone}</strong> performance that <strong>{comp}</strong> industry standards.</p>"

        html = f"""
        <section class="report">
            <header class="report__header">
                <h2>{title}</h2>
                <div class="report__meta">Generated: {self.report_date}</div>
                <div class="badge badge--{badge_class}">{rating}</div>
            </header>
            <article class="report__body">
                {exec_summary_html}
                {metrics_html}
            </article>
            <footer class="report__footer">
                <p>Generated by Hospitality AI Agent</p>
            </footer>
        </section>
        """

        return {"text": text.strip(), "html": html}

    def format_labor_analysis(self, labor_costs: float, total_sales: float,
                            labor_hours: float) -> dict:
        """
        Format labor analysis into a professional report
        Returns dict with 'text' and 'html' keys
        """
        labor_percentage = (labor_costs / total_sales) * 100 if total_sales > 0 else 0
        productivity = total_sales / labor_hours if labor_hours > 0 else 0

        # Determine rating
        if labor_percentage < 20:
            rating = "Excellent"
        elif labor_percentage < 25:
            rating = "Good"
        elif labor_percentage < 30:
            rating = "Acceptable"
        else:
            rating = "Needs Improvement"

        metrics = [
            {
                'title': 'Labor Cost Percentage',
                'calculation': '(Total Labor Costs / Total Sales) × 100',
                'example': f'(${labor_costs:,.2f} / ${total_sales:,.2f}) × 100 = {labor_percentage:.1f}%',
                'interpretation': self._interpret_labor_percentage(labor_percentage),
                'recommendations': self._get_labor_recommendations(labor_percentage)
            },
            {
                'title': 'Labor Productivity',
                'calculation': 'Sales / Labor Hours',
                'example': f'${total_sales:,.2f} / {labor_hours:.0f} hours = ${productivity:.2f} per hour',
                'interpretation': self._interpret_productivity(productivity),
                'recommendations': self._get_productivity_recommendations(productivity)
            }
        ]

        executive_summary = f"Your restaurant's labor efficiency analysis shows a {labor_percentage:.1f}% labor cost ratio and ${productivity:.2f} in sales per labor hour. {'This indicates strong operational efficiency' if labor_percentage < 25 else 'There are opportunities for optimization'} in your labor management strategy."

        return self.format_comprehensive_report("Labor Efficiency Analysis", metrics, executive_summary, rating)

    def format_kpi_analysis(self, kpi_data: Dict[str, Any]) -> dict:
        """
        Format KPI analysis into a professional report
        Returns dict with 'text' and 'html' keys
        """
        metrics = []
        ratings = []

        for kpi_name, kpi_info in kpi_data.items():
            metrics.append({
                'title': kpi_info.get('title', kpi_name),
                'calculation': kpi_info.get('calculation', ''),
                'example': kpi_info.get('example', ''),
                'interpretation': kpi_info.get('interpretation', ''),
                'recommendations': kpi_info.get('recommendations', [])
            })
            # Track ratings if provided
            if 'assessment' in kpi_info:
                ratings.append(kpi_info['assessment'])

        # Determine overall rating
        if ratings:
            if all(r == 'excellent' for r in ratings):
                rating = "Excellent"
            elif any(r == 'needs_improvement' for r in ratings):
                rating = "Needs Improvement"
            else:
                rating = "Good"
        else:
            rating = "Good"

        executive_summary = f"Comprehensive KPI analysis covering {len(metrics)} key performance indicators. This report provides actionable insights to optimize your restaurant's operational efficiency."

        return self.format_comprehensive_report("Key Performance Indicators Analysis", metrics, executive_summary, rating)

    def format_inventory_analysis(self, inventory_data: Dict[str, Any]) -> dict:
        """
        Format inventory analysis into a professional report
        Returns dict with 'text' and 'html' keys
        """
        metrics = []

        for item, data in inventory_data.items():
            metrics.append({
                'title': f'Inventory Analysis - {item}',
                'calculation': data.get('calculation', ''),
                'example': data.get('example', ''),
                'interpretation': data.get('interpretation', ''),
                'recommendations': data.get('recommendations', [])
            })

        executive_summary = f"Inventory optimization analysis covering {len(metrics)} key inventory metrics. This report helps identify cost-saving opportunities and improve inventory turnover."

        return self.format_comprehensive_report("Inventory Optimization Analysis", metrics, executive_summary)

    def _interpret_labor_percentage(self, percentage: float) -> str:
        """Interpret labor cost percentage"""
        if percentage < 20:
            return f"A labor cost percentage of {percentage:.1f}% is considered excellent and indicates strong operational efficiency. This is well below industry standards of 20-30%."
        elif percentage < 25:
            return f"A labor cost percentage of {percentage:.1f}% is considered good and within acceptable range. This is slightly below industry standards of 20-30%."
        elif percentage < 30:
            return f"A labor cost percentage of {percentage:.1f}% is at the upper limit of industry standards (20-30%). Consider optimization strategies."
        else:
            return f"A labor cost percentage of {percentage:.1f}% exceeds industry standards (20-30%). Immediate action is recommended to improve labor efficiency."

    def _get_labor_recommendations(self, percentage: float) -> List[str]:
        """Get labor cost recommendations"""
        if percentage > 25:
            return [
                "Implement dynamic scheduling based on sales forecasts",
                "Cross-train staff to handle multiple roles during peak hours",
                "Review and optimize staff schedules to match business patterns",
                "Consider automation for repetitive tasks"
            ]
        else:
            return [
                "Maintain current efficiency levels",
                "Continue monitoring labor costs regularly",
                "Consider staff development programs to maintain quality"
            ]

    def _interpret_productivity(self, productivity: float) -> str:
        """Interpret labor productivity"""
        if productivity > 50:
            return f"Labor productivity of ${productivity:.2f} per hour is excellent and indicates highly efficient operations."
        elif productivity > 30:
            return f"Labor productivity of ${productivity:.2f} per hour is good and shows effective labor utilization."
        elif productivity > 20:
            return f"Labor productivity of ${productivity:.2f} per hour is average. There's room for improvement in efficiency."
        else:
            return f"Labor productivity of ${productivity:.2f} per hour is below optimal. Immediate attention to labor efficiency is recommended."

    def _get_productivity_recommendations(self, productivity: float) -> List[str]:
        """Get productivity recommendations"""
        if productivity < 30:
            return [
                "Analyze peak hours and optimize staffing accordingly",
                "Implement performance tracking for individual staff members",
                "Review operational processes for efficiency improvements",
                "Consider staff training programs to improve productivity"
            ]
        else:
            return [
                "Maintain current productivity levels",
                "Continue monitoring and benchmarking against industry standards",
                "Share best practices across all shifts"
            ]


def format_business_insight(title: str, calculation: str, example: str,
                          interpretation: str, recommendations: List[str] = None) -> dict:
    """
    Convenience function to format a single business insight
    Returns dict with 'text' and 'html' keys for backward compatibility also returns the text directly
    """
    formatter = BusinessReportFormatter()
    result = formatter.format_metric_card(title, calculation, example, interpretation, recommendations)
    # For backward compatibility, return text string but functions should use the dict
    return result


def format_comprehensive_analysis(analysis_type: str, data: Dict[str, Any]) -> dict:
    """
    Convenience function to format comprehensive analysis
    Returns dict with 'text' and 'html' keys
    """
    formatter = BusinessReportFormatter()

    if analysis_type.lower() == 'labor':
        return formatter.format_labor_analysis(
            data.get('labor_costs', 0),
            data.get('total_sales', 0),
            data.get('labor_hours', 0)
        )
    elif analysis_type.lower() == 'kpi':
        return formatter.format_kpi_analysis(data)
    elif analysis_type.lower() == 'inventory':
        return formatter.format_inventory_analysis(data)
    else:
        # Generic comprehensive report
        metrics = []
        for key, value in data.items():
            if isinstance(value, dict):
                metrics.append(value)

        return formatter.format_comprehensive_report(f"{analysis_type.title()} Analysis", metrics)
